defaults:
  - _self_
  - agent: potil
  - suite: dmc
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/oldhome/cw/workspace/cross-embodiment/ROT'

# replay buffer
replay_buffer_size: 150000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256 # 128
# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true

# experiment
obs_type: 'pixels' # pixels, features
experiment: bc_${suite.name}_${obs_type}_fs${suite.frame_stack}_${task_name}_seed_${seed}

# expert dataset
num_demos: 10 #50(openaigym), 10(dmc), 1(metaworld), 1(particle), 1(robotgym)
expert_dataset: '${root_dir}/ROT/expert_demos/expert_demos_224x224_fs${suite.frame_stack}/${suite.name}/${task_name}/expert_demos.pkl'

# Load weights
load_bc: false

# Weights
bc_weight: '${root_dir}/ROT/weights/${suite.name}_${obs_type}/${task_name}/bc.pt'

# Train with BC loss
bc_regularize: false
bc_weight_type: 'qfilter' # linear, qfilter

hydra:
  run:
#    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
    dir: /nvme/cw/result/cross_embodiment/ROT/exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
#    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    dir: /nvme/cw/result/cross_embodiment/ROT/exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
